hp_portal:
  path: /
  defaults: { _controller: hkpeter.controller.portal:portalAction }

hp_portal_get:
  path: /keys/{fingerprint}
  defaults: { _controller: hkpeter.controller.portal:getAction }

hp_portal_post:
  path: /keys
  defaults: { _controller: hkpeter.controller.portal:addAction }
