parameters:
  hkpeter.key_repository.gnupg.class: elseym\HKPeterBundle\KeyRepository\GnupgKeyRepository
  hkpeter.key_repository.random.class: elseym\HKPeterBundle\KeyRepository\RandomKeyRepository

services:
  hkpeter.key_repository.gnupg:
    class: %hkpeter.key_repository.gnupg.class%
    calls:
      - [ setGnupgService, [ @hkpeter.service.gnupg ] ]

  hkpeter.key_repository.random:
    class: %hkpeter.key_repository.random.class%
    calls:
      - [ setWordService, [ @hkpeter.service.word ] ]
