parameters:
  hkpeter.service.gnupg.class: elseym\HKPeterBundle\Service\GnupgService
  hkpeter.service.word.class: elseym\HKPeterBundle\Service\WordService

services:
  hkpeter.service.gnupg:
    class: %hkpeter.service.gnupg.class%
    private: true
    calls:
      - [ setGnupgBin, [ %hkpeter.gnupg.bin% ] ]

  hkpeter.service.word:
    class: %hkpeter.service.word.class%
    private: true
