parameters:
  hkpeter.service.gnupg_cli.class: elseym\HKPeterBundle\Service\GnupgCliService
  hkpeter.service.word.class: elseym\HKPeterBundle\Service\WordService
  hkpeter.service.sp_bower_post_install.class: elseym\HKPeterBundle\Service\SpBowerPostInstallService

services:
  hkpeter.service.gnupg_cli:
    class: %hkpeter.service.gnupg_cli.class%
    private: true
    calls:
      - [ setGnupgBin, [ %hkpeter.gnupg_cli.bin% ] ]
      - [ setGnupgHomedir, [ %hkpeter.gnupg_cli.homedir% ] ]
      - [ setGnupgArgs, [ %hkpeter.gnupg_cli.args% ] ]

  hkpeter.service.word:
    class: %hkpeter.service.word.class%
    private: true

  hkpeter.service.sp_bower_post_install:
    class: %hkpeter.service.sp_bower_post_install.class%
    calls:
      - [ setFilesystem, [ @filesystem ] ]
      - [ setOutputDirectory, [ %assetic.write_to% ] ]
      - [ setAssets, [ %bower_assets% ] ]
    tags:
      - { name: kernel.event_listener, event: bower.post_install, method: copyAssets }
      - { name: kernel.event_listener, event: bower.post_update, method: copyAssets }
