parameters:
  hkpeter.service.gnupg_cli.class: elseym\HKPeterBundle\Service\GnupgCliService
  hkpeter.service.word.class: elseym\HKPeterBundle\Service\WordService
  hkpeter.service.sp_bower_post_install.class: elseym\HKPeterBundle\Service\SpBowerPostInstallService
  hkpeter.service.pgpdump_cli.class: elseym\HKPeterBundle\Service\PgpdumpCliService
  hkpeter.factory.key_factory.class: elseym\HKPeterBundle\Factory\KeyFactory
  hkpeter.form.add_key.class: elseym\HKPeterBundle\Form\Type\AddKeyType

services:
  hkpeter.service.gnupg_cli:
    class: %hkpeter.service.gnupg_cli.class%
    private: true
    lazy: true
    calls:
      - [ setGnupgBin, [ %hkpeter.gnupg_cli.bin% ] ]
      - [ setGnupgHomedir, [ %hkpeter.gnupg_cli.homedir% ] ]
      - [ setGnupgArgs, [ %hkpeter.gnupg_cli.args% ] ]
      - [ setFilesystem, [ @filesystem ] ]

  hkpeter.service.pgpdump_cli:
    class: %hkpeter.service.pgpdump_cli.class%
    calls:
      - [ setPgpdumpBin, [ %hkpeter.pgpdump_cli.bin% ] ]

  hkpeter.factory.key_factory:
    class: %hkpeter.factory.key_factory.class%
    calls:
      - [ setGnupgService, [ @hkpeter.service.gnupg_cli ] ]

  hkpeter.service.word:
    class: %hkpeter.service.word.class%
    private: true

  hkpeter.service.sp_bower_post_install:
    class: %hkpeter.service.sp_bower_post_install.class%
    calls:
      - [ setFilesystem, [ @filesystem ] ]
      - [ setOutputDirectory, [ %assetic.write_to% ] ]
      - [ setAssets, [ %bower_assets% ] ]
    tags:
      - { name: kernel.event_listener, event: bower.post_install, method: copyAssets }
      - { name: kernel.event_listener, event: bower.post_update, method: copyAssets }

  #form services
  hkpeter.form.add_key:
    class: %hkpeter.form.add_key.class%
    tags:
      - { name: form.type, alias: add_key }
