elseym_hkp_server:
    resource: "@elseymHKPServerBundle/Resources/config/routing.yml"
    prefix:   /pks

elseym_hk_peter:
    resource: "@elseymHKPeterBundle/Resources/config/routing.yml"
    prefix:   /

